name: Build and Push the Images to the ECR Repository
on: 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1


   # Build and push the MySQL Docker image
    - name: Build the MySQL Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: mysql-repo
        IMAGE_TAG: mysql-v1
      run: |
        ls -ltra
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile_mysql .
        docker run -d --name mysql-container -e MYSQL_ROOT_PASSWORD=root $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker ps
        echo "Pause for 10 seconds to let MySQL container start"
        sleep 10
        docker exec mysql-container mysql -uroot -proot -e "SHOW DATABASES;"
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
    

    # Build and push the Web Application Docker image
    - name: Build the Web Application Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: web-app-repo
        IMAGE_TAG: webapp-v1
      run: |
        ls -ltra
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
        # docker run -d -p 80:8080 --name my-webapp-container $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        # docker ps
        # echo "Pause for 10 seconds to let web app container start"
        # sleep 10
        # curl localhost -vvv
        # # Push web app image to ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG